version: '3'

services:
  flask-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  nextjs-app:
  	build:
  	  context: ./frontend
  	  dockerfile: Dockerfile
  	ports:
  	  - 3000:3000
  	volumes:
  	  - ./frontend/trading_app:/app  
  		       
      

